type: Sqlite # Avaiable types: mongo, mysql, sqlite


# MONGO
Mongo:
  connection-string: "mongodb://<username>:<password>@<host>:<port>/"
  database: "db"


# mysql
SQL:
  connection-string: "jdbc:sqlite:path/to/db/sample.db"
  username: "username" # Not required for sqlite
  password: "password" # Not required for sqlite

# sqlite

